name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "root"
          host: "62.171.186.163"
          password: "8BSqG4WVbp9WFr"
          script: "cd /home/vmi370585/public_html/API-Gateway && ./server_deploy.sh"
