name: Laravel
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Config composer
      run: composer config --global --auth http-basic.ride-to-the-future.repo.repman.io token 67001fefcf70038c817987b7431f2d17498dc5c2409b4748e51cad87a69b8567
    - name: Install Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  laravel-deploy:
    runs-on: vmi627964
    needs: laravel-tests
    steps:
    - uses: actions/checkout@v2
    - name: Copy project to deployment directory
      run: |
        shopt -s dotglob 
        sudo mkdir -p /home/stagingapigateway/public_html/API-Gateway/temp-project 
        sudo cp -r . /home/stagingapigateway/public_html/API-Gateway/temp-project/
        sudo chown -R stagingapigateway:stagingapigateway /home/stagingapigateway/public_html/API-Gateway/temp-project
    - name: Run server_deploy.sh
      run: | 
        sudo su - stagingapigateway -c '/home/stagingapigateway/public_html/API-Gateway/server_deploy.sh'
